<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: protos/queue.proto
 */

declare(strict_types=1);

namespace Thesis\Queue;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class ProtosQueueDescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'ChJwcm90b3MvcXVldWUucHJvdG8SDFRoZXNpcy5RdWV1ZSIyCgtQdXNoUmVxdWVzdBojCgdNZXNzYWdlEhgKB2NvbnRlbnQYASABKAlSB2NvbnRlbnQiVAoLUHVsbFJlcXVlc3QSEAoDcW9zGAEgASgFUgNxb3MaMwoHTWVzc2FnZRIYCgdjb250ZW50GAEgASgJUgdjb250ZW50Eg4KAmlkGAIgASgJUgJpZCI3CglIZWFydGJlYXQaFAoKRnJvbVNlcnZlchoGCgRQaW5nGhQKCkZyb21DbGllbnQaBgoEUGluZ0qGBAoGEgQAABsBCggKAQwSAwAAEgoICgECEgMCABUKCgoCBAASBAQACAEKCgoDBAABEgMECBMKDAoEBAADABIEBQQHBQoMCgUEAAMAARIDBQwTCg0KBgQAAwACABIDBggbCg4KBwQAAwACAAUSAwYIDgoOCgcEAAMAAgABEgMGDxYKDgoHBAADAAIAAxIDBhkaCgoKAgQBEgQKABEBCgoKAwQBARIDCggTCgwKBAQBAwASBAsEDgUKDAoFBAEDAAESAwsMEwoNCgYEAQMAAgASAwwIGwoOCgcEAQMAAgAFEgMMCA4KDgoHBAEDAAIAARIDDA8WCg4KBwQBAwACAAMSAwwZGgoNCgYEAQMAAgESAw0IFgoOCgcEAQMAAgEFEgMNCA4KDgoHBAEDAAIBARIDDQ8RCg4KBwQBAwACAQMSAw0UFQoLCgQEAQIAEgMQBBIKDAoFBAECAAUSAxAECQoMCgUEAQIAARIDEAoNCgwKBQQBAgADEgMQEBEKCgoCBAISBBMAGwEKCgoDBAIBEgMTCBEKDAoEBAIDABIEFAQWBQoMCgUEAgMAARIDFAwWCg0KBgQCAwADABIDFQgXCg4KBwQCAwADAAESAxUQFAoMCgQEAgMBEgQYBBoFCgwKBQQCAwEBEgMYDBYKDQoGBAIDAQMAEgMZCBcKDgoHBAIDAQMAARIDGRAUYgZwcm90bzM=';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'protos/queue.proto',
            messages: [
                new File\MessageDescriptor('Thesis.Queue.PushRequest', \Thesis\Queue\PushRequest::class),
                new File\MessageDescriptor('Thesis.Queue.PushRequest.Message', \Thesis\Queue\PushRequest\Message::class),
                new File\MessageDescriptor('Thesis.Queue.PullRequest', \Thesis\Queue\PullRequest::class),
                new File\MessageDescriptor('Thesis.Queue.PullRequest.Message', \Thesis\Queue\PullRequest\Message::class),
                new File\MessageDescriptor('Thesis.Queue.Heartbeat', \Thesis\Queue\Heartbeat::class),
                new File\MessageDescriptor('Thesis.Queue.Heartbeat.FromServer', \Thesis\Queue\Heartbeat\FromServer::class),
                new File\MessageDescriptor('Thesis.Queue.Heartbeat.FromServer.Ping', \Thesis\Queue\Heartbeat\FromServer\Ping::class),
                new File\MessageDescriptor('Thesis.Queue.Heartbeat.FromClient', \Thesis\Queue\Heartbeat\FromClient::class),
                new File\MessageDescriptor('Thesis.Queue.Heartbeat.FromClient.Ping', \Thesis\Queue\Heartbeat\FromClient\Ping::class),
            ],
        ));
    }
}
