<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 */

declare(strict_types=1);

\Thesis\Protobuf\Registry\Pool::get()->register(
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Thesis\Auth\V1\AuthV1DescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Thesis\Auth\ProtosAuthDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Thesis\Queue\ProtosQueueDescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Thesis\Queue\V1\QueueV1DescriptorRegistry()),
);
