<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: reserved_names/reserved_names.proto
 */

declare(strict_types=1);

namespace ReservedTypes\Class_\Case_;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Break_
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $name = '',
    ) {}
}
