<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto3/test.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1\TestRequest;

/**
 * @api
 * @phpstan-sealed (
 *   ContactPhone |
 *   ContactEmail
 * )
 */
interface Contact {}
