<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto3/test.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1\TestRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class ContactEmail implements \Proto\Api\V1\TestRequest\Contact
{
    public function __construct(
        #[Reflection\Field(4, Reflection\StringT::T)]
        public string $email = '',
    ) {}
}
