<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: snake_case/snake_case.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1\TestRequest\NestedMessage;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Deep
{
    public function __construct(
        #[Reflection\Field(3, new Reflection\EnumT(\Proto\Api\V1\TestRequest\NestedMessage\Deep\DeepEnum::class))]
        public ?\Proto\Api\V1\TestRequest\NestedMessage\Deep\DeepEnum $deepEnum = null,
        #[Reflection\OneOf([
            \Proto\Api\V1\TestRequest\NestedMessage\Deep\UnionPhone::class,
            \Proto\Api\V1\TestRequest\NestedMessage\Deep\UnionEmail::class,
        ])]
        public ?\Proto\Api\V1\TestRequest\NestedMessage\Deep\Union $union = null,
    ) {}
}
