<?php

declare(strict_types=1);

namespace Thesis\Protoc\Plugin;

use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\EnumCase;
use Nette\PhpGenerator\EnumType;
use Nette\PhpGenerator\Literal;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PhpNamespace;
use Nette\PhpGenerator\PsrPrinter;
use Thesis\Protobuf\Compiler\FieldDescriptorProto\Label;
use Thesis\Protobuf\Compiler\Plugin\CodeGeneratorResponse;
use Thesis\Protobuf\Map;
use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Generator
{
    private PsrPrinter $printer;

    /** @var non-empty-string */
    private string $generatedDoc;

    private AggregateTypeDeclarationResolver $typeDeclarationResolver;

    /**
     * @param non-empty-string $namespace
     * @param non-empty-string $path
     * @param non-empty-string $library
     * @param non-empty-string $pluginVersion
     */
    public function __construct(
        private string $namespace,
        private string $path,
        string $library,
        string $pluginVersion,
        string $protocVersion,
        string $source,
        private ?string $package = null,
    ) {
        $this->printer = new Printer();
        $this->typeDeclarationResolver = new AggregateTypeDeclarationResolver([
            new KnownTypeDeclarationResolver(),
            new NativeTypeDeclarationResolver(),
            new CustomTypeDeclarationResolver(),
        ]);
        $this->generatedDoc = vsprintf(
            <<<'DOC'
Code generated by %1$s. DO NOT EDIT.
Versions:
  %1$s — v%2$s
  protoc — v%3$s
Source: %4$s
DOC,
            [
                $library,
                $pluginVersion,
                $protocVersion,
                $source,
            ],
        );
    }

    public function generateMessage(MessageDescriptor $message): CodeGeneratorResponse\File
    {
        $classType = new ClassType(Naming::pascalCase($message->name))
            ->addComment('@api')
            ->addComment($message->comment !== null ? "\n{$message->comment}" : '')
            ->setFinal()
            ->setReadOnly();

        $namespace = $this->createPhpNamespace($message->path);

        $namespace->add($classType);

        if (\count($message->fields) > 0) {
            $namespace->addUse('Thesis\Protobuf\Reflection');

            $constructor = $classType->addMethod('__construct');

            foreach ($message->fields as $field) {
                $parameter = $constructor->addPromotedParameter(Naming::camelCase($field->name));

                $type = null;

                if ($field->typeName !== null) {
                    foreach ($message->messages as $messageType) {
                        if (isMapEntry($messageType) && $field->typeName === ".{$this->package}.{$messageType->path}") {
                            \assert(\count($messageType->fields) === 2, 'MapEntry must have 2 fields.');

                            $keyType = $this->typeDeclarationResolver->resolve(
                                $messageType->fields[0],
                                $namespace,
                            );

                            $valueType = $this->typeDeclarationResolver->resolve(
                                $messageType->fields[1],
                                $namespace,
                            );

                            $type = new TypeDeclaration(
                                phpType: Map::class,
                                reflectionType: Literal::new('Reflection\MapT', [
                                    $keyType->reflectionType,
                                    $valueType->reflectionType,
                                ]),
                                uses: [
                                    'Thesis\Protobuf',
                                ],
                                nullable: false,
                                default: Literal::new($mapType = 'Protobuf\Map'),
                                docType: "{$mapType}<{$keyType->resolvedType()}, {$valueType->resolvedType()}>",
                                isMap: true,
                            );
                        }
                    }
                }

                $type ??= $this->typeDeclarationResolver->resolve($field, $namespace);

                foreach ($type->uses as $use) {
                    $namespace->addUse($use);
                }

                $repeated = $field->label === Label::LABEL_REPEATED && !$type->isMap;

                $nullable = ($type->nullable || $field->optional) && !$repeated;

                $phpType = $repeated ? 'array' : $type->phpType;
                if ($nullable) {
                    $phpType = "?{$phpType}";
                }

                $reflectionType = $type->reflectionType;
                if ($repeated) {
                    $reflectionType = Literal::new('Reflection\ListT', [$reflectionType]);
                }

                $parameter
                    ->setType($phpType)
                    ->addAttribute(Reflection\Field::class, [
                        $field->number,
                        $reflectionType,
                    ])
                    ->setNullable($nullable)
                    ->setDefaultValue($nullable ? null : ($repeated ? [] : $type->default));

                if ($repeated || $field->comment !== null || $type->isMap) {
                    $docType = $type->resolvedType();

                    if ($repeated) {
                        $docType = "list<{$docType}>";
                    }

                    if ($nullable) {
                        $docType = "?{$docType}";
                    }

                    $comment = "@param {$docType} \${$parameter->getName()}";
                    if ($field->comment !== null) {
                        $comment .= " {$field->comment}";
                    }

                    $constructor->addComment($comment);
                }
            }
        }

        return $this->createFile(
            $namespace,
            $message->path,
        );
    }

    public function generateEnum(EnumDescriptor $enum): CodeGeneratorResponse\File
    {
        $namespace = $this->createPhpNamespace($enum->path);

        $enumType = new EnumType(Naming::pascalCase($enum->name))
            ->addComment('@api')
            ->addComment($enum->comment !== null ? "\n{$enum->comment}" : '')
            ->setType('int')
            ->setCases(array_map(
                static fn(EnumCaseDescriptor $case) => new EnumCase($case->name)
                    ->setValue($case->value)
                    ->setComment((string) $case->comment),
                $enum->cases,
            ));

        $namespace->add($enumType);

        return $this->createFile($namespace, $enum->path);
    }

    private function createFile(
        PhpNamespace $namespace,
        string $path,
    ): CodeGeneratorResponse\File {
        $file = new PhpFile()
            ->setStrictTypes()
            ->setComment($this->generatedDoc)
            ->add($namespace);

        return new CodeGeneratorResponse\File(
            name: \sprintf('%s/%s.php', $this->path, str_replace('.', '/', $path)),
            content: $this->printer->printFile($file),
        );
    }

    private function createPhpNamespace(string $path): PhpNamespace
    {
        $namespace = $this->namespace;

        $paths = explode('.', $path);
        $typeNamespace = \array_slice($paths, 0, \count($paths) - 1);
        if (\count($typeNamespace) > 0) {
            $namespace .= '\\' . implode('\\', $typeNamespace);
        }

        return new PhpNamespace($namespace);
    }
}
