<?php

declare(strict_types=1);

namespace Thesis\Protoc\Plugin;

use Nette\PhpGenerator\ClassType;
use Nette\PhpGenerator\EnumCase;
use Nette\PhpGenerator\EnumType;
use Nette\PhpGenerator\InterfaceType;
use Nette\PhpGenerator\Literal;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PhpNamespace;
use Nette\PhpGenerator\PsrPrinter;
use Thesis\Protobuf\Compiler\FieldDescriptorProto\Label;
use Thesis\Protobuf\Compiler\FieldDescriptorProto\Type;
use Thesis\Protobuf\Compiler\Plugin\CodeGeneratorResponse;
use Thesis\Protobuf\Map;
use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Generator
{
    private PsrPrinter $printer;

    /** @var non-empty-string */
    private string $generatedDoc;

    private AggregateTypeDeclarationResolver $typeDeclarationResolver;

    /**
     * @param non-empty-string $namespace
     * @param non-empty-string $path
     * @param non-empty-string $pluginVersion
     */
    public function __construct(
        private string $namespace,
        private string $path,
        string $pluginVersion,
        string $protocVersion,
        string $source,
        private ?string $package = null,
        private ?string $syntax = null,
    ) {
        $this->printer = new Printer();
        $this->typeDeclarationResolver = new AggregateTypeDeclarationResolver([
            new KnownTypeDeclarationResolver(),
            new NativeTypeDeclarationResolver(),
            new CustomTypeDeclarationResolver(),
        ]);
        $this->generatedDoc = vsprintf(
            <<<'DOC'
Code generated by thesis/protoc-plugin. DO NOT EDIT.
Versions:
  thesis/protoc-plugin — v%s
  protoc               — v%s
Source: %s
DOC,
            [
                $pluginVersion,
                $protocVersion,
                $source,
            ],
        );
    }

    /**
     * @return iterable<CodeGeneratorResponse\File>
     */
    public function generateMessages(MessageDescriptor $message): iterable
    {
        yield $this->generateMessage($message);

        $oneofByIndex = [];

        foreach ($message->fields as $field) {
            if ($field->oneOfIndex !== null && $field->proto3Optional === null) {
                if (isset($message->oneofs[$field->oneOfIndex])) {
                    $oneOf = $message->oneofs[$field->oneOfIndex];

                    yield $this->generateOneofVariant(
                        $message,
                        $oneOf,
                        $field,
                    );

                    $oneofByIndex[$field->oneOfIndex][] = $field;
                }
            }
        }

        foreach ($message->oneofs as $idx => $oneof) {
            $variants = $oneofByIndex[$idx] ?? [];

            if ($variants !== []) {
                yield $this->generateOneof($message, $oneof, $variants);
            }
        }
    }

    public function generateEnum(EnumDescriptor $enum): CodeGeneratorResponse\File
    {
        $namespace = $this->createPhpNamespace($enum->path);

        $enumType = new EnumType(Naming::pascalCase($enum->name))
            ->addComment('@api')
            ->addComment($enum->comment !== null ? "\n{$enum->comment}" : '')
            ->setType('int')
            ->setCases(array_map(
                static fn(EnumCaseDescriptor $case) => new EnumCase($case->name)
                    ->setValue($case->value)
                    ->setComment((string) $case->comment),
                $enum->cases,
            ));

        $namespace->add($enumType);

        return $this->createFile($namespace, $enum->path);
    }

    /**
     * @param list<string> $implements
     */
    private function generateMessage(MessageDescriptor $message, array $implements = []): CodeGeneratorResponse\File
    {
        $className = Naming::pascalCase($message->name);

        $classType = new ClassType($className)
            ->addComment('@api')
            ->addComment($message->comment !== null ? "\n{$message->comment}" : '')
            ->setFinal()
            ->setImplements($implements)
            ->setReadOnly();

        $namespace = $this->createPhpNamespace($message->path);

        $namespace->add($classType);

        if (\count($message->fields) > 0) {
            $namespace->addUse('Thesis\Protobuf\Reflection');

            $constructor = $classType->addMethod('__construct');

            $oneOfByIndex = [];

            foreach ($message->fields as $field) {
                if ($field->oneOfIndex !== null && $field->proto3Optional === null) {
                    $oneOfByIndex[$field->oneOfIndex][] = $field;

                    continue;
                }

                $parameter = $constructor->addPromotedParameter(Naming::camelCase($field->name));

                $type = null;

                if ($field->typeName !== null) {
                    foreach ($message->messages as $messageType) {
                        if (isMapEntry($messageType) && $field->typeName === ".{$this->package}.{$messageType->path}") {
                            \assert(\count($messageType->fields) === 2, 'MapEntry must have 2 fields.');

                            $keyType = $this->typeDeclarationResolver->resolve(
                                $messageType->fields[0],
                                $namespace,
                            );

                            $valueType = $this->typeDeclarationResolver->resolve(
                                $messageType->fields[1],
                                $namespace,
                            );

                            $type = new TypeDeclaration(
                                phpType: Map::class,
                                reflectionType: Literal::new('Reflection\MapT', [
                                    $keyType->reflectionType,
                                    $valueType->reflectionType,
                                ]),
                                uses: [
                                    'Thesis\Protobuf',
                                    ...$keyType->uses,
                                    ...$valueType->uses,
                                ],
                                nullable: false,
                                default: Literal::new('Protobuf\Map'),
                                docType: "Protobuf\\Map<{$keyType->resolvedType()}, {$valueType->resolvedType()}>",
                                isMap: true,
                            );

                            break;
                        }
                    }
                }

                $type ??= $this->typeDeclarationResolver->resolve($field, $namespace);

                foreach ($type->uses as $use) {
                    $namespace->addUse($use);
                }

                $repeated = $field->label === Label::LABEL_REPEATED && !$type->isMap;

                $nullable = ($type->nullable || $field->optional) && !$repeated;

                $phpType = ($nullable ? '?' : '') . ($repeated ? 'array' : $type->phpType);

                $reflectionType = $type->reflectionType;

                if ($repeated) {
                    $listParameters = [$reflectionType];

                    // In proto2 all repeated fields are non-packed by default unless explicitly marked with [packed = true].
                    if ($this->syntax === null) {
                        $listParameters[] = $field->options?->packed === true;
                    }

                    $reflectionType = Literal::new('Reflection\ListT', $listParameters);
                }

                $default = $type->default;

                // In proto2 (and only there) scalar fields can have default values set.
                if ($this->syntax === null && $field->defaultValue !== null && $field->type !== null) {
                    $default = $this->parseDefaultValue($field->type, $field->defaultValue);
                } elseif ($nullable) {
                    $default = null;
                }

                $parameter
                    ->setType($phpType)
                    ->addAttribute(Reflection\Field::class, [
                        $field->number,
                        $reflectionType,
                    ])
                    ->setNullable($nullable)
                    ->setDefaultValue($repeated ? [] : $default);

                if ($repeated || $field->comment !== null || $type->isMap) {
                    $docType = $type->resolvedType();

                    if ($repeated) {
                        $docType = "list<{$docType}>";
                    }

                    if ($nullable) {
                        $docType = "?{$docType}";
                    }

                    $comment = "@param {$docType} \${$parameter->getName()}";
                    if ($field->comment !== null) {
                        $comment .= " {$field->comment}";
                    }

                    $constructor->addComment($comment);
                }
            }

            foreach ($oneOfByIndex as $idx => $variants) {
                if (!isset($message->oneofs[$idx])) {
                    continue;
                }

                $oneOf = $message->oneofs[$idx];

                $oneOfName = Naming::pascalCase($oneOf->name);

                $constructor
                    ->addPromotedParameter(Naming::camelCase($oneOf->name))
                    ->setType(Naming::joinNamespace([
                        $this->namespace,
                        $message->path,
                        $oneOfName,
                    ]))
                    ->setNullable()
                    ->setDefaultValue(null)
                    ->addAttribute(Reflection\OneOf::class, [
                        array_map(
                            static fn(FieldDescriptor $variant) => new Literal(
                                \sprintf("{$className}\\{$oneOfName}%s::class", Naming::pascalCase($variant->name)),
                            ),
                            $variants,
                        ),
                    ]);
            }
        }

        return $this->createFile(
            $namespace,
            $message->path,
        );
    }

    /**
     * @param list<FieldDescriptor> $variants
     */
    private function generateOneof(
        MessageDescriptor $message,
        OneOfDescriptor $oneof,
        array $variants,
    ): CodeGeneratorResponse\File {
        $interfaceName = Naming::pascalCase($oneof->name);

        $interfaceType = new InterfaceType($interfaceName)
            ->addComment('@api')
            ->addComment('@phpstan-sealed (')
            ->addComment(implode(" |\n", array_map(
                static fn(FieldDescriptor $variant) => \sprintf('  %s%s', $interfaceName, Naming::pascalCase($variant->name)),
                $variants,
            )))
            ->addComment(')');

        $path = "{$message->path}.{$interfaceType->getName()}";

        $namespace = $this->createPhpNamespace($path);

        $namespace->add($interfaceType);

        return $this->createFile(
            $namespace,
            $path,
        );
    }

    private function generateOneofVariant(
        MessageDescriptor $message,
        OneOfDescriptor $oneof,
        FieldDescriptor $variant,
    ): CodeGeneratorResponse\File {
        $interfaceName = Naming::pascalCase($oneof->name);
        $className = \sprintf('%s%s', $interfaceName, Naming::pascalCase($variant->name));

        $descriptor = new MessageDescriptor(
            name: $className,
            path: "{$message->path}.{$className}",
            fields: [
                // Remove oneof index.
                new FieldDescriptor(
                    name: $variant->name,
                    number: $variant->number,
                    label: $variant->label,
                    type: $variant->type,
                    typeName: $variant->typeName,
                    comment: $variant->comment,
                    options: $variant->options,
                    optional: $variant->optional,
                ),
            ],
        );

        return $this->generateMessage($descriptor, [
            Naming::joinNamespace([
                $this->namespace,
                $message->path,
                $interfaceName,
            ]),
        ]);
    }

    private function createFile(
        PhpNamespace $namespace,
        string $path,
    ): CodeGeneratorResponse\File {
        $file = new PhpFile()
            ->setStrictTypes()
            ->setComment($this->generatedDoc)
            ->add($namespace);

        return new CodeGeneratorResponse\File(
            name: \sprintf('%s/%s.php', $this->path, str_replace('.', '/', $path)),
            content: $this->printer->printFile($file),
        );
    }

    private function createPhpNamespace(string $path): PhpNamespace
    {
        $namespace = $this->namespace;

        $paths = explode('.', $path);
        $typeNamespace = \array_slice($paths, 0, \count($paths) - 1);
        if (\count($typeNamespace) > 0) {
            $namespace .= '\\' . implode('\\', $typeNamespace);
        }

        return new PhpNamespace($namespace);
    }

    private function parseDefaultValue(
        Type $type,
        string $defaultValue,
    ): mixed {
        return match ($type) {
            Type::TYPE_STRING,
            Type::TYPE_BYTES => $defaultValue,
            Type::TYPE_INT32,
            Type::TYPE_SINT32,
            Type::TYPE_UINT32,
            Type::TYPE_FIXED32,
            Type::TYPE_SFIXED32 => filter_var($defaultValue, FILTER_VALIDATE_INT, FILTER_NULL_ON_FAILURE) ?? 0,
            Type::TYPE_INT64,
            Type::TYPE_SINT64,
            Type::TYPE_UINT64,
            Type::TYPE_FIXED64,
            Type::TYPE_SFIXED64 => Literal::new('Number', [
                filter_var($defaultValue, FILTER_VALIDATE_INT, FILTER_NULL_ON_FAILURE) ?? 0,
            ]),
            Type::TYPE_BOOL => filter_var($defaultValue, FILTER_VALIDATE_BOOLEAN),
            Type::TYPE_FLOAT,
            Type::TYPE_DOUBLE => filter_var($defaultValue, FILTER_VALIDATE_FLOAT),
            default => null,
        };
    }
}
