<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: status.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Rpc\Status;

/**
 * @api
 */
enum Kind: int
{
    case KIND_UNSPECIFIED = 0;
    case KIND_RETRYABLE = 1;
}
