<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: status.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Rpc\Status;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class PayloadStructured implements \Thesis\Google\Rpc\Status\Payload
{
    public function __construct(
        #[Reflection\Field(6, new Reflection\ObjectT(\Thesis\Google\Rpc\Status\Detail::class))]
        public ?\Thesis\Google\Rpc\Status\Detail $structured = null,
    ) {}
}
