<?php

declare(strict_types=1);

namespace Thesis\Protoc;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use Thesis\Protobuf\Compiler\Plugin\CodeGeneratorRequest;
use Thesis\Protobuf\Compiler\Plugin\CodeGeneratorResponse;
use Thesis\Protobuf\Reflection\Reflector;
use Thesis\Protobuf\Serializer;
use Thesis\Protoc\Plugin\Compiler;

#[CoversClass(Compiler::class)]
final class CompilerTest extends TestCase
{
    #[DataProvider('provideCompileCases')]
    public function testCompile(string $file, CodeGeneratorResponse $response): void
    {
        $hex = file_get_contents(__DIR__ . "/testdata/{$file}");
        self::assertIsString($hex);

        $bytes = hex2bin($hex);
        self::assertIsString($bytes);

        $serializer = new Serializer();
        $reflector = Reflector::build();

        $request = $reflector->map(
            $serializer->deserialize($reflector->type(CodeGeneratorRequest::class), $bytes),
            CodeGeneratorRequest::class,
        );

        self::assertEquals($response, new Compiler()->compile($request));
    }

    /**
     * @return iterable<array{non-empty-string, CodeGeneratorResponse}>
     */
    public static function provideCompileCases(): iterable
    {
        yield [
            'proto2/test.txt',
            new CodeGeneratorResponse(
                supportFeatures: Compiler::SUPPORTED_FEATURES,
                files: [
                    new CodeGeneratorResponse\File(
                        name: 'Proto/Api/V1/Foo.php',
                        content: self::phpContent(
                            'proto2/test.proto',
                            <<<'PHP'
namespace Proto\Api\V1;

/**
 * @api
 */
enum Foo: int
{
    case FOO_UNSPECIFIED = 0;
    case FOO_BAR = 1;
    case FOO_BAZ = 2;
}

PHP,
                        ),
                    ),
                ],
            ),
        ];
    }

    private static function phpContent(string $source, string $content): string
    {
        return \sprintf(
            <<<'PHP'
<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v%s
 *   protoc               — v6.32.1
 * Source: %s
 */

declare(strict_types=1);

%s
PHP,
            Compiler::PLUGIN_VERSION,
            $source,
            $content,
        );
    }
}
