<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto2.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1\TestRequest;

/**
 * @api
 *
 * Nested enum comment.
 */
enum Kind: int
{
    /** Nested enum comment case. */
    case KIND_UNSPECIFIED = 0;
    case VOID = 1;
    case STRING = 2;
    case BOOL = 3;
}
