<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto2.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1\TestRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Comment on nested message.
 */
final readonly class Nested
{
    /**
     * @param ?string $name Comment on nested message field.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public ?string $name = null,
        #[Reflection\Field(2, Reflection\StringT::T)]
        public ?string $group = null,
        #[Reflection\Field(3, new Reflection\ObjectT(\Proto\Api\V1\TestRequest\Nested\Deep::class))]
        public ?\Proto\Api\V1\TestRequest\Nested\Deep $deep = null,
    ) {}
}
