<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto2.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1\TestRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class XFieldData implements \Proto\Api\V1\TestRequest\XField
{
    public function __construct(
        #[Reflection\Field(7, Reflection\BytesT::T)]
        public ?string $data = null,
    ) {}
}
