<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: underscore_collision/test.proto
 */

declare(strict_types=1);

namespace PgQuery\Node;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class NodeList implements \PgQuery\Node\Node
{
    public function __construct(
        #[Reflection\Field(268, new Reflection\ObjectT(\PgQuery\List_::class))]
        public ?\PgQuery\List_ $List = null,
    ) {}
}
