<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: underscore_collision/test.proto
 */

declare(strict_types=1);

namespace PgQuery\Node;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class NodeBitString implements \PgQuery\Node\Node
{
    public function __construct(
        #[Reflection\Field(267, new Reflection\ObjectT(\PgQuery\BitString::class))]
        public ?\PgQuery\BitString $BitString = null,
    ) {}
}
