<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: snake_case.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1\TestRequest;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class XFieldNumber implements \Proto\Api\V1\TestRequest\XField
{
    public function __construct(
        #[Reflection\Field(2, Reflection\Int32T::T)]
        public int $number = 0,
    ) {}
}
