<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto2.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class AnotherRequest
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Proto\Api\V1\TestRequest\Nested::class))]
        public ?\Proto\Api\V1\TestRequest\Nested $nested = null,
        #[Reflection\Field(2, new Reflection\ObjectT(\Proto\Api\V1\TestRequest\Nested\Deep::class))]
        public ?\Proto\Api\V1\TestRequest\Nested\Deep $deep = null,
        #[Reflection\Field(3, new Reflection\EnumT(\Proto\Api\V1\TestRequest\Kind::class))]
        public ?\Proto\Api\V1\TestRequest\Kind $kind = null,
        #[Reflection\Field(4, new Reflection\EnumT(\Proto\Api\V1\TestRequest\Nested\Deep\DeepEnum::class))]
        public ?\Proto\Api\V1\TestRequest\Nested\Deep\DeepEnum $deepEnum = null,
    ) {}
}
