<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: editions.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class EditionsFeatures
{
    /**
     * @param list<int> $packed
     * @param list<int> $expanded
     * @param list<int> $defaultEncoding
     * @param \Proto\Api\V1\Type $type Default type is TYPE_EDITIONS.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $implicit = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public ?string $explicit = null,
        #[Reflection\Field(3, Reflection\StringT::T)]
        public string $defaultPresence = '',
        #[Reflection\Field(4, new Reflection\ListT(Reflection\Int32T::T, true))]
        public array $packed = [],
        #[Reflection\Field(5, new Reflection\ListT(Reflection\Int32T::T, false))]
        public array $expanded = [],
        #[Reflection\Field(6, new Reflection\ListT(Reflection\Int32T::T, true))]
        public array $defaultEncoding = [],
        #[Reflection\Field(7, new Reflection\EnumT(\Proto\Api\V1\Type::class))]
        public \Proto\Api\V1\Type $type = \Proto\Api\V1\Type::TYPE_EDITIONS,
    ) {}
}
