<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: editions.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class EditionsDescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Cg5lZGl0aW9ucy5wcm90bxIMcHJvdG8uYXBpLnYxIqcCChBFZGl0aW9uc0ZlYXR1cmVzEiEKCGltcGxpY2l0GAEgASgJUghpbXBsaWNpdEIFqgECCAISIQoIZXhwbGljaXQYAiABKAlSCGV4cGxpY2l0QgWqAQIIARIpChBkZWZhdWx0X3ByZXNlbmNlGAMgASgJUg9kZWZhdWx0UHJlc2VuY2USHQoGcGFja2VkGAQgAygFUgZwYWNrZWRCBaoBAhgBEiEKCGV4cGFuZGVkGAUgAygFUghleHBhbmRlZEIFqgECGAISKQoQZGVmYXVsdF9lbmNvZGluZxgGIAMoBVIPZGVmYXVsdEVuY29kaW5nEjUKBHR5cGUYByABKA4yEi5wcm90by5hcGkudjEuVHlwZToNVFlQRV9FRElUSU9OU1IEdHlwZSo+CgRUeXBlEhIKEFRZUEVfVU5TUEVDSUZJRUQSDwoLVFlQRV9QUk9UTzMQARIRCg1UWVBFX0VESVRJT05TEAJKqAYKBhIEAAATAQoICgEMEgMAABEKCAoBAhIDAgAVCgoKAgUAEgQEAAgBCgoKAwUAARIDBAUJCgsKBAUAAgASAwUEGQoMCgUFAAIAARIDBQQUCgwKBQUAAgACEgMFFxgKCwoEBQACARIDBgQUCgwKBQUAAgEBEgMGBA8KDAoFBQACAQISAwYSEwoLCgQFAAICEgMHBBYKDAoFBQACAgESAwcEEQoMCgUFAAICAhIDBxQVCgoKAgQAEgQKABMBCgoKAwQAARIDCggYCgsKBAQAAgASAwsEPQoMCgUEAAIABRIDCwQKCgwKBQQAAgABEgMLCxMKDAoFBAACAAMSAwsWFwoMCgUEAAIACBIDCxg8Cg4KBwQAAgAIFQESAwsZOwoLCgQEAAIBEgMMBD0KDAoFBAACAQUSAwwECgoMCgUEAAIBARIDDAsTCgwKBQQAAgEDEgMMFhcKDAoFBAACAQgSAwwYPAoOCgcEAAIBCBUBEgMMGTsKCwoEBAACAhIDDQQgCgwKBQQAAgIFEgMNBAoKDAoFBAACAgESAw0LGwoMCgUEAAICAxIDDR4fCgsKBAQAAgMSAw4ESgoMCgUEAAIDBBIDDgQMCgwKBQQAAgMFEgMODRIKDAoFBAACAwESAw4TGQoMCgUEAAIDAxIDDhwdCgwKBQQAAgMIEgMOHkkKDgoHBAACAwgVAxIDDh9ICgsKBAQAAgQSAw8ETgoMCgUEAAIEBBIDDwQMCgwKBQQAAgQFEgMPDRIKDAoFBAACBAESAw8TGwoMCgUEAAIEAxIDDx4fCgwKBQQAAgQIEgMPIE0KDgoHBAACBAgVAxIDDyFMCgsKBAQAAgUSAxAEKAoMCgUEAAIFBBIDEAQMCgwKBQQAAgUFEgMQDRIKDAoFBAACBQESAxATIwoMCgUEAAIFAxIDECYnCi0KBAQAAgYSAxIELBogIERlZmF1bHQgdHlwZSBpcyBUWVBFX0VESVRJT05TLgoKDAoFBAACBgYSAxIECAoMCgUEAAIGARIDEgkNCgwKBQQAAgYDEgMSEBEKDAoFBAACBggSAxISKwoMCgUEAAIGBxIDEh0qYghlZGl0aW9uc3DoBw==';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'editions.proto',
            messages: [
                new File\MessageDescriptor('proto.api.v1.EditionsFeatures', \Proto\Api\V1\EditionsFeatures::class),
            ],
            enums: [
                new File\EnumDescriptor('proto.api.v1.Type', \Proto\Api\V1\Type::class),
            ],
        ));
    }
}
