<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: editions/test.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1;

/**
 * @api
 */
enum Type: int
{
    case TYPE_UNSPECIFIED = 0;
    case TYPE_PROTO3 = 1;
    case TYPE_EDITIONS = 2;
}
