<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: protos/auth.proto
 */

declare(strict_types=1);

namespace Thesis\Auth;

use Override;
use Thesis\Protobuf\Pool;
use Thesis\Protobuf\Pool\File;

/**
 * @api
 */
final readonly class ProtosAuthDescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'ChFwcm90b3MvYXV0aC5wcm90bxILVGhlc2lzLkF1dGgiPgoMTG9naW5SZXF1ZXN0EhIKBHVzZXIYAiABKAlSBHVzZXISGgoIcGFzc3dvcmQYAyABKAlSCHBhc3N3b3JkIiUKDUxvZ2luUmVzcG9uc2USFAoFdG9rZW4YASABKAlSBXRva2VuSvEBCgYSBAAACwEKCAoBDBIDAAASCggKAQISAwIAFAoKCgIEABIEBAAHAQoKCgMEAAESAwQIFAoLCgQEAAIAEgMFBBQKDAoFBAACAAUSAwUECgoMCgUEAAIAARIDBQsPCgwKBQQAAgADEgMFEhMKCwoEBAACARIDBgQYCgwKBQQAAgEFEgMGBAoKDAoFBAACAQESAwYLEwoMCgUEAAIBAxIDBhYXCgoKAgQBEgQJAAsBCgoKAwQBARIDCQgVCgsKBAQBAgASAwoEFQoMCgUEAQIABRIDCgQKCgwKBQQBAgABEgMKCxAKDAoFBAECAAMSAwoTFGIGcHJvdG8z';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'protos/auth.proto',
            messages: [
                new File\MessageDescriptor('Thesis.Auth.LoginRequest', \Thesis\Auth\LoginRequest::class),
                new File\MessageDescriptor('Thesis.Auth.LoginResponse', \Thesis\Auth\LoginResponse::class),
            ],
        ));
    }
}
