<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: deprecated.proto
 */

declare(strict_types=1);

namespace Test\Api\V1;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class DeprecatedDescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'ChBkZXByZWNhdGVkLnByb3RvEgt0ZXN0LmFwaS52MSJSCgdSZXF1ZXN0EhYKBG5hbWUYASABKAlSBG5hbWVCAhgBGisKDU5lc3RlZFJlcXVlc3QSFgoEbmFtZRgBIAEoCVIEbmFtZUICGAE6AhgBOgIYASo1CgRUeXBlEhgKEFRZUEVfVU5TUEVDSUZJRUQQABoCCAESDwoLVFlQRV9QUk9UTzMQARoCGAEySwoLRWNob1NlcnZpY2USNwoERWNobxIULnRlc3QuYXBpLnYxLlJlcXVlc3QaFC50ZXN0LmFwaS52MS5SZXF1ZXN0IgOIAgEaA4gCAUq+BgoGEgQAACUBCggKAQwSAwAAEgoICgECEgMCABQKIQoCBQASBAUACwEaFSBUeXBlIGlzIGRlcHJlY2F0ZWQuCgoKCgMFAAESAwUFCQoKCgMFAAMSAwYEHQoLCgQFAAMDEgMGBB0KIgoEBQACABIDCQQtGhUgQ2FzZSBpcyBkZXByZWNhdGVkLgoKDAoFBQACAAESAwkEFAoMCgUFAAIAAhIDCRcYCgwKBQUAAgADEgMJGSwKDQoGBQACAAMBEgMJGisKCwoEBQACARIDCgQUCgwKBQUAAgEBEgMKBA8KDAoFBQACAQISAwoSEwokCgIEABIEDgAbARoYIFJlcXVlc3QgaXMgZGVwcmVjYXRlZC4KCgoKAwQAARIDDggPCgoKAwQABxIDDwQdCgsKBAQABwMSAw8EHQojCgQEAAIAEgMSBCgaFiBGaWVsZCBpcyBkZXByZWNhdGVkLgoKDAoFBAACAAUSAxIECgoMCgUEAAIAARIDEgsPCgwKBQQAAgADEgMSEhMKDAoFBAACAAgSAxIUJwoNCgYEAAIACAMSAxIVJgoyCgQEAAMAEgQVBBoFGiQgTmVzdGVkIG1lc3NhZ2UgaXMgYWxzbyBkZXByZWNhdGVkLgoKDAoFBAADAAESAxUMGQoMCgUEAAMABxIDFgghCg0KBgQAAwAHAxIDFgghCjAKBgQAAwACABIDGQgsGiEgTmVzdGVkIGZpZWxkIGlzIGRlcHJlY2F0ZWQgdG9vLgoKDgoHBAADAAIABRIDGQgOCg4KBwQAAwACAAESAxkPEwoOCgcEAAMAAgADEgMZFhcKDgoHBAADAAIACBIDGRgrCg8KCAQAAwACAAgDEgMZGSoKJAoCBgASBB4AJQEaGCBTZXJ2aWNlIGlzIGRlcHJlY2F0ZWQuCgoKCgMGAAESAx4IEwoKCgMGAAMSAx8EHQoLCgQGAAMhEgMfBB0KJwoEBgACABIEIgQkBRoZIFJwYyBpcyBhbHNvIGRlcHJlY2F0ZWQuCgoMCgUGAAIAARIDIggMCgwKBQYAAgACEgMiDRQKDAoFBgACAAMSAyIfJgoMCgUGAAIABBIDIwghCg0KBgYAAgAEIRIDIwghYgZwcm90bzM=';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'deprecated.proto',
            messages: [
                new File\MessageDescriptor('test.api.v1.Request', \Test\Api\V1\Request::class),
                new File\MessageDescriptor('test.api.v1.Request.NestedRequest', \Test\Api\V1\Request\NestedRequest::class),
            ],
            enums: [
                new File\EnumDescriptor('test.api.v1.Type', \Test\Api\V1\Type::class),
            ],
            services: [
                new File\ServiceDescriptor(
                    name: 'test.api.v1.EchoService',
                    methods: [
                        new File\MethodDescriptor('Echo', false, false),
                    ],
                ),
            ],
        ));
    }
}
