<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: deprecated.proto
 */

declare(strict_types=1);

namespace Test\Api\V1;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class DeprecatedDescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'ChBkZXByZWNhdGVkLnByb3RvEgt0ZXN0LmFwaS52MSJSCgdSZXF1ZXN0EhYKBG5hbWUYASABKAlSBG5hbWVCAhgBGisKDU5lc3RlZFJlcXVlc3QSFgoEbmFtZRgBIAEoCVIEbmFtZUICGAE6AhgBOgIYASo1CgRUeXBlEhgKEFRZUEVfVU5TUEVDSUZJRUQQABoCCAESDwoLVFlQRV9QUk9UTzMQARoCGAFKgwUKBhIEAAAbAQoICgEMEgMAABIKCAoBAhIDAgAUCiEKAgUAEgQFAAsBGhUgVHlwZSBpcyBkZXByZWNhdGVkLgoKCgoDBQABEgMFBQkKCgoDBQADEgMGBB0KCwoEBQADAxIDBgQdCiIKBAUAAgASAwkELRoVIENhc2UgaXMgZGVwcmVjYXRlZC4KCgwKBQUAAgABEgMJBBQKDAoFBQACAAISAwkXGAoMCgUFAAIAAxIDCRksCg0KBgUAAgADARIDCRorCgsKBAUAAgESAwoEFAoMCgUFAAIBARIDCgQPCgwKBQUAAgECEgMKEhMKJAoCBAASBA4AGwEaGCBSZXF1ZXN0IGlzIGRlcHJlY2F0ZWQuCgoKCgMEAAESAw4IDwoKCgMEAAcSAw8EHQoLCgQEAAcDEgMPBB0KIwoEBAACABIDEgQoGhYgRmllbGQgaXMgZGVwcmVjYXRlZC4KCgwKBQQAAgAFEgMSBAoKDAoFBAACAAESAxILDwoMCgUEAAIAAxIDEhITCgwKBQQAAgAIEgMSFCcKDQoGBAACAAgDEgMSFSYKMgoEBAADABIEFQQaBRokIE5lc3RlZCBtZXNzYWdlIGlzIGFsc28gZGVwcmVjYXRlZC4KCgwKBQQAAwABEgMVDBkKDAoFBAADAAcSAxYIIQoNCgYEAAMABwMSAxYIIQowCgYEAAMAAgASAxkILBohIE5lc3RlZCBmaWVsZCBpcyBkZXByZWNhdGVkIHRvby4KCg4KBwQAAwACAAUSAxkIDgoOCgcEAAMAAgABEgMZDxMKDgoHBAADAAIAAxIDGRYXCg4KBwQAAwACAAgSAxkYKwoPCggEAAMAAgAIAxIDGRkqYgZwcm90bzM=';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'deprecated.proto',
            messages: [
                new File\MessageDescriptor('test.api.v1.Request', \Test\Api\V1\Request::class),
                new File\MessageDescriptor('test.api.v1.Request.NestedRequest', \Test\Api\V1\Request\NestedRequest::class),
            ],
            enums: [
                new File\EnumDescriptor('test.api.v1.Type', \Test\Api\V1\Type::class),
            ],
        ));
    }
}
