<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: deprecated.proto
 */

declare(strict_types=1);

namespace Test\Api\V1;

use Amp\Cancellation;
use Amp\NullCancellation;
use Deprecated;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 * @deprecated
 *
 * Service is deprecated.
 */
final readonly class EchoServiceClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * Rpc is also deprecated.
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    #[Deprecated]
    public function echo(
        \Test\Api\V1\Request $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Test\Api\V1\Request {
        /** @var Client\Invoke<\Test\Api\V1\Request, \Test\Api\V1\Request> $invoke */
        $invoke = new Client\Invoke(
            method: '/test.api.v1.EchoService/Echo',
            type: \Test\Api\V1\Request::class,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
