<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: deprecated.proto
 */

declare(strict_types=1);

namespace Test\Api\V1;

use Amp\Cancellation;
use Deprecated;
use Thesis\Grpc\Metadata;

/**
 * @api
 * @deprecated
 *
 * Service is deprecated.
 */
interface EchoServiceServer
{
    /**
     * Rpc is also deprecated.
     */
    #[Deprecated]
    public function echo(
        \Test\Api\V1\Request $request,
        Metadata $md,
        Cancellation $cancellation,
    ): \Test\Api\V1\Request;
}
