<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: deprecated.proto
 */

declare(strict_types=1);

namespace Test\Api\V1;

use Override;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class EchoServiceServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \Test\Api\V1\EchoServiceServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('test.api.v1.EchoService', [
            new Server\Rpc(
                new Server\Handle('Echo', \Test\Api\V1\Request::class),
                new Server\UnaryHandler($this->server->echo(...)),
                Server\RpcType::Unary,
            ),
        ]);
    }
}
