<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: deprecated.proto
 */

declare(strict_types=1);

namespace Test\Api\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 * @deprecated
 *
 * Request is deprecated.
 */
final readonly class Request
{
    /**
     * @param string $name Field is deprecated.
     */
    public function __construct(
        /** @deprecated */
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $name = '',
    ) {}
}
