<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: deprecated.proto
 */

declare(strict_types=1);

namespace Test\Api\V1;

/**
 * @api
 * @deprecated
 *
 * Type is deprecated.
 */
enum Type: int
{
    /**
     * @deprecated
     *
     * Case is deprecated.
     */
    case TYPE_UNSPECIFIED = 0;
    case TYPE_PROTO3 = 1;
}
