<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: test.proto
 */

declare(strict_types=1);

namespace Tmp\NoPkg;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class A
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Tmp\NoPkg\B::class))]
        public ?\Tmp\NoPkg\B $b = null,
    ) {}
}
