<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: test.proto
 */

declare(strict_types=1);

namespace Tmp\NoPkg;

use Override;
use Thesis\Protobuf\Pool;
use Thesis\Protobuf\Pool\File;

/**
 * @api
 */
final readonly class TestDescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Cgp0ZXN0LnByb3RvIhUKAUESEAoBYhgBIAEoCzICLkJSAWIiEQoBQhIMCgF2GAEgASgJUgF2Qg/4AQHKAglUbXBcTm9Qa2dKxQEKBhIEAAAKAQoICgEMEgMAABIKCAoBCBIDAgAkCgkKAggpEgMCACQKCgoCBAASBAQABgEKCgoDBAABEgMECAkKCwoEBAACABIDBQIKCgwKBQQAAgAGEgMFAgMKDAoFBAACAAESAwUEBQoMCgUEAAIAAxIDBQgJCgoKAgQBEgQIAAoBCgoKAwQBARIDCAgJCgsKBAQBAgASAwkCDwoMCgUEAQIABRIDCQIICgwKBQQBAgABEgMJCQoKDAoFBAECAAMSAwkNDmIGcHJvdG8z';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'test.proto',
            messages: [
                new File\MessageDescriptor('A', \Tmp\NoPkg\A::class),
                new File\MessageDescriptor('B', \Tmp\NoPkg\B::class),
            ],
        ));
    }
}
