<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: code.proto
 */

declare(strict_types=1);

namespace Multi\Pkg\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * Two files share one package, so the plugin must emit a single
 * DescriptorRegistry with a CODE_DESCRIPTOR_BUFFER / STATUS_DESCRIPTOR_BUFFER
 * constant per file instead of two colliding DescriptorRegistry.php.
 */
final readonly class Code
{
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public int $value = 0,
    ) {}
}
