<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: code.proto, status.proto
 */

declare(strict_types=1);

namespace Multi\Pkg\V1;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class DescriptorRegistry implements Registry\Registrar
{
    private const string CODE_DESCRIPTOR_BUFFER = 'Cgpjb2RlLnByb3RvEgxtdWx0aS5wa2cudjEiHAoEQ29kZRIUCgV2YWx1ZRgBIAEoBVIFdmFsdWVKvwIKBhIEAAAJAQoICgEMEgMAABIKCAoBAhIDAgAVCt0BCgIEABIEBwAJARrQASBUd28gZmlsZXMgc2hhcmUgb25lIHBhY2thZ2UsIHNvIHRoZSBwbHVnaW4gbXVzdCBlbWl0IGEgc2luZ2xlCiBEZXNjcmlwdG9yUmVnaXN0cnkgd2l0aCBhIENPREVfREVTQ1JJUFRPUl9CVUZGRVIgLyBTVEFUVVNfREVTQ1JJUFRPUl9CVUZGRVIKIGNvbnN0YW50IHBlciBmaWxlIGluc3RlYWQgb2YgdHdvIGNvbGxpZGluZyBEZXNjcmlwdG9yUmVnaXN0cnkucGhwLgoKCgoDBAABEgMHCAwKCwoEBAACABIDCAQUCgwKBQQAAgAFEgMIBAkKDAoFBAACAAESAwgKDwoMCgUEAAIAAxIDCBITYgZwcm90bzM=';
    private const string STATUS_DESCRIPTOR_BUFFER = 'CgxzdGF0dXMucHJvdG8SDG11bHRpLnBrZy52MRoKY29kZS5wcm90byJKCgZTdGF0dXMSGAoHbWVzc2FnZRgBIAEoCVIHbWVzc2FnZRImCgRjb2RlGAIgASgLMhIubXVsdGkucGtnLnYxLkNvZGVSBGNvZGVKrQEKBhIEAAAJAQoICgEMEgMAABIKCAoBAhIDAgAVCgkKAgMAEgMEABQKCgoCBAASBAYACQEKCgoDBAABEgMGCA4KCwoEBAACABIDBwQXCgwKBQQAAgAFEgMHBAoKDAoFBAACAAESAwcLEgoMCgUEAAIAAxIDBxUWCgsKBAQAAgESAwgEEgoMCgUEAAIBBhIDCAQICgwKBQQAAgEBEgMICQ0KDAoFBAACAQMSAwgQEWIGcHJvdG8z';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::CODE_DESCRIPTOR_BUFFER), new File(
            name: 'code.proto',
            messages: [
                new File\MessageDescriptor('multi.pkg.v1.Code', \Multi\Pkg\V1\Code::class),
            ],
        ));

        $pool->add(Registry\Descriptor::base64(self::STATUS_DESCRIPTOR_BUFFER), new File(
            name: 'status.proto',
            dependencies: [
                'code.proto',
            ],
            messages: [
                new File\MessageDescriptor('multi.pkg.v1.Status', \Multi\Pkg\V1\Status::class),
            ],
        ));
    }
}
