<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: status.proto
 */

declare(strict_types=1);

namespace Multi\Pkg\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Status
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $message = '',
        #[Reflection\Field(2, new Reflection\ObjectT(\Multi\Pkg\V1\Code::class))]
        public ?\Multi\Pkg\V1\Code $code = null,
    ) {}
}
