<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: auth_v1.proto
 */

declare(strict_types=1);

namespace Thesis\Auth\V1;

use Override;
use Thesis\Grpc;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class AuthServiceServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \Thesis\Auth\V1\AuthServiceServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('Thesis.Auth.V1.AuthService', [
            new Server\Rpc(
                handle: new Server\Handle('Login', \Thesis\Auth\LoginRequest::class),
                handler: new Server\UnaryHandler($this->server->login(...)),
                type: Grpc\RpcType::Unary,
            ),
        ]);
    }
}
