<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: auth_v1.proto
 */

declare(strict_types=1);

namespace Thesis\Auth\V1;

use Amp\Cancellation;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
interface AuthServiceServer
{
    public function login(
        \Thesis\Auth\LoginRequest $request,
        Metadata $md,
        Cancellation $cancellation,
    ): \Thesis\Auth\LoginResponse;
}
