<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: pg_query.proto
 */

declare(strict_types=1);

namespace PgQuery;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class DescriptorRegistry implements Registry\Registrar
{
    private const string PG_QUERY_DESCRIPTOR_BUFFER = 'Cg5wZ19xdWVyeS5wcm90bxIIcGdfcXVlcnkiXAoETm9kZRJMChJydGVwZXJtaXNzaW9uX2luZm8YYyABKAsyGy5wZ19xdWVyeS5SVEVQZXJtaXNzaW9uSW5mb0gAUhFSVEVQZXJtaXNzaW9uSW5mb0IGCgRub2RlIiUKEVJURVBlcm1pc3Npb25JbmZvEhAKA2luaBgCIAEoCFIDaW5oSqoCCgYSBAAADQEKCAoBDBIDAAASCggKAQISAwIAEQoKCgIEABIEBAAIAQoKCgMEAAESAwQIDAoMCgQEAAgAEgQFBAcFCgwKBQQACAABEgMFCg4KCwoEBAACABIDBghSCgwKBQQAAgAGEgMGCBkKDAoFBAACAAESAwYaLAoMCgUEAAIAAxIDBi8xCgwKBQQAAgAIEgMGMlEKDAoFBAACAAoSAwYzUAoMCgUEAAIAChIDBj1QCgoKAgQBEgQKAA0BCgoKAwQBARIDCggZCgsKBAQBAgASAwwEIwoMCgUEAQIABRIDDAQICgwKBQQBAgABEgMMCQwKDAoFBAECAAMSAwwPEAoMCgUEAQIACBIDDBEiCgwKBQQBAgAKEgMMEiEKDAoFBAECAAoSAwwcIWIGcHJvdG8z';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::PG_QUERY_DESCRIPTOR_BUFFER), new File(
            name: 'pg_query.proto',
            messages: [
                new File\MessageDescriptor('pg_query.Node', \PgQuery\Node::class),
                new File\MessageDescriptor('pg_query.RTEPermissionInfo', \PgQuery\RTEPermissionInfo::class),
            ],
        ));
    }
}
