<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: pg_query.proto
 */

declare(strict_types=1);

namespace PgQuery;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class RTEPermissionInfo
{
    public function __construct(
        #[Reflection\Field(2, Reflection\BoolT::T)]
        public bool $inh = false,
    ) {}
}
