<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: reserved_names/reserved_names.proto
 */

declare(strict_types=1);

namespace ReservedTypes;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Class_
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\ReservedTypes\Class_\Case_\Break_::class))]
        public ?\ReservedTypes\Class_\Case_\Break_ $break = null,
    ) {}
}
