<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: reserved_names/reserved_names.proto
 */

declare(strict_types=1);

namespace ReservedTypes;

/**
 * @api
 */
final readonly class Exit_ {}
