<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: reserved_names.proto
 */

declare(strict_types=1);

namespace ReservedTypes;

/**
 * @api
 */
enum NotAllowed: int
{
    case abstract = 0;
    case and = 1;
    case array = 2;
    case empty = 3;
    case class_ = 4;
}
