<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: reserved_names.proto
 */

declare(strict_types=1);

namespace ReservedTypes;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class ReservedNamesDescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'ChRyZXNlcnZlZF9uYW1lcy5wcm90bxIOcmVzZXJ2ZWRfdHlwZXMiBgoEZXhpdCJECgpJTlNUQU5DRU9GEjYKBWJyZWFrGAEgASgLMiAucmVzZXJ2ZWRfdHlwZXMuQ2xhc3MuQ2FzZS5CcmVha1IFYnJlYWsiZAoFQ2xhc3MSNgoFYnJlYWsYASABKAsyIC5yZXNlcnZlZF90eXBlcy5DbGFzcy5DYXNlLkJyZWFrUgVicmVhaxojCgRDYXNlGhsKBUJyZWFrEhIKBG5hbWUYASABKAlSBG5hbWUqRAoKTm90QWxsb3dlZBIMCghhYnN0cmFjdBAAEgcKA2FuZBABEgkKBWFycmF5EAISCQoFZW1wdHkQAxIJCgVjbGFzcxAEKhMKBnN0cmluZxIJCgVaRVJPMRAAKhIKBVRyYWl0EgkKBVpFUk8yEABKuQUKBhIEAAAeAQoICgEMEgMAABIKCAoBAhIDAgAXCgoKAgUAEgQEAAoBCgoKAwUAARIDBAUPCgsKBAUAAgASAwUEEQoMCgUFAAIAARIDBQQMCgwKBQUAAgACEgMFDxAKCwoEBQACARIDBgQMCgwKBQUAAgEBEgMGBAcKDAoFBQACAQISAwYKCwoLCgQFAAICEgMHBA4KDAoFBQACAgESAwcECQoMCgUFAAICAhIDBwwNCgsKBAUAAgMSAwgEDgoMCgUFAAIDARIDCAQJCgwKBQUAAgMCEgMIDA0KCwoEBQACBBIDCQQOCgwKBQUAAgQBEgMJBAkKDAoFBQACBAISAwkMDQoJCgIFARIDDAAaCgoKAwUBARIDDAULCgsKBAUBAgASAwwOGAoMCgUFAQIAARIDDA4TCgwKBQUBAgACEgMMFhcKCQoCBQISAw4AGQoKCgMFAgESAw4FCgoLCgQFAgIAEgMODRcKDAoFBQICAAESAw4NEgoMCgUFAgIAAhIDDhUWCgkKAgQAEgMQAA8KCgoDBAABEgMQCAwKCgoCBAESBBIAFAEKCgoDBAEBEgMSCBIKCwoEBAECABIDEwQfCgwKBQQBAgAGEgMTBBQKDAoFBAECAAESAxMVGgoMCgUEAQIAAxIDEx0eCgoKAgQCEgQWAB4BCgoKAwQCARIDFggNCgwKBAQCAwASBBcEGwUKDAoFBAIDAAESAxcMEAoOCgYEAgMAAwASBBgIGgkKDgoHBAIDAAMAARIDGBAVCg8KCAQCAwADAAIAEgMZDBwKEAoJBAIDAAMAAgAFEgMZDBIKEAoJBAIDAAMAAgABEgMZExcKEAoJBAIDAAMAAgADEgMZGhsKCwoEBAICABIDHQQZCgwKBQQCAgAGEgMdBA4KDAoFBAICAAESAx0PFAoMCgUEAgIAAxIDHRcYYgZwcm90bzM=';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'reserved_names.proto',
            messages: [
                new File\MessageDescriptor('reserved_types.exit', \ReservedTypes\Exit_::class),
                new File\MessageDescriptor('reserved_types.INSTANCEOF', \ReservedTypes\INSTANCEOF_::class),
                new File\MessageDescriptor('reserved_types.Class', \ReservedTypes\Class_::class),
                new File\MessageDescriptor('reserved_types.Class.Case', \ReservedTypes\Class_\Case_::class),
                new File\MessageDescriptor('reserved_types.Class.Case.Break', \ReservedTypes\Class_\Case_\Break_::class),
            ],
            enums: [
                new File\EnumDescriptor('reserved_types.NotAllowed', \ReservedTypes\NotAllowed::class),
                new File\EnumDescriptor('reserved_types.string', \ReservedTypes\String_::class),
                new File\EnumDescriptor('reserved_types.Trait', \ReservedTypes\Trait_::class),
            ],
        ));
    }
}
