<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: underscore_collision/test.proto
 */

declare(strict_types=1);

namespace PgQuery;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Float_
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $fval = '',
    ) {}
}
