<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: underscore_collision/test.proto
 */

declare(strict_types=1);

namespace PgQuery;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class List_
{
    /**
     * @param list<\PgQuery\Node> $items
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(new Reflection\ObjectT(\PgQuery\Node::class)))]
        public array $items = [],
    ) {}
}
