<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: underscore_collision/test.proto
 */

declare(strict_types=1);

namespace PgQuery;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Node
{
    public function __construct(
        #[Reflection\OneOf([
            \PgQuery\Node\NodeInteger::class,
            \PgQuery\Node\NodeFloat::class,
            \PgQuery\Node\NodeBoolean::class,
            \PgQuery\Node\NodeString::class,
            \PgQuery\Node\NodeBitString::class,
            \PgQuery\Node\NodeList::class,
        ])]
        public ?\PgQuery\Node\Node $node = null,
    ) {}
}
