<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: queue_v1.proto
 */

declare(strict_types=1);

namespace Thesis\Queue\V1;

use Override;
use Thesis\Grpc;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class QueueServiceServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \Thesis\Queue\V1\QueueServiceServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('Thesis.Queue.V1.QueueService', [
            new Server\Rpc(
                handle: new Server\Handle('Push', \Thesis\Queue\PushRequest\Message::class),
                handler: new Server\ClientStreamHandler($this->server->push(...)),
                type: Grpc\RpcType::ClientStream,
            ),
            new Server\Rpc(
                handle: new Server\Handle('Pull', \Thesis\Queue\PullRequest::class),
                handler: new Server\ServerStreamHandler($this->server->pull(...)),
                type: Grpc\RpcType::ServerStream,
            ),
            new Server\Rpc(
                handle: new Server\Handle('Heartbeat', \Thesis\Queue\Heartbeat\FromClient\Ping::class),
                handler: new Server\BidirectionalStreamHandler($this->server->heartbeat(...)),
                type: Grpc\RpcType::BidirectionalStream,
            ),
        ]);
    }
}
