<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: queue_v1.proto
 */

declare(strict_types=1);

namespace Thesis\Queue\V1;

use Amp\Cancellation;
use Thesis\Grpc\Metadata;
use Thesis\Grpc\Server;

/**
 * @api
 */
interface QueueServiceServer
{
    /**
     * @param Server\ClientStreamChannel<\Thesis\Queue\PushRequest\Message, \Google\Protobuf\Empty_> $stream
     */
    public function push(
        Server\ClientStreamChannel $stream,
        Metadata $md,
        Cancellation $cancellation,
    ): \Google\Protobuf\Empty_;

    /**
     * @return iterable<array-key, \Thesis\Queue\PullRequest\Message>
     */
    public function pull(\Thesis\Queue\PullRequest $request, Metadata $md, Cancellation $cancellation): iterable;

    /**
     * @param Server\BidirectionalStreamChannel<\Thesis\Queue\Heartbeat\FromClient\Ping, \Thesis\Queue\Heartbeat\FromServer\Ping> $stream
     */
    public function heartbeat(
        Server\BidirectionalStreamChannel $stream,
        Metadata $md,
        Cancellation $cancellation,
    ): void;
}
