<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: pgquery.proto
 */

declare(strict_types=1);

namespace PgQuery;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class PgqueryDescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Cg1wZ3F1ZXJ5LnByb3RvEghwZ19xdWVyeSJcCgROb2RlEkwKEnJ0ZXBlcm1pc3Npb25faW5mbxhjIAEoCzIbLnBnX3F1ZXJ5LlJURVBlcm1pc3Npb25JbmZvSABSEVJURVBlcm1pc3Npb25JbmZvQgYKBG5vZGUiJQoRUlRFUGVybWlzc2lvbkluZm8SEAoDaW5oGAIgASgIUgNpbmhKqgIKBhIEAAANAQoICgEMEgMAABIKCAoBAhIDAgARCgoKAgQAEgQEAAgBCgoKAwQAARIDBAgMCgwKBAQACAASBAUEBwUKDAoFBAAIAAESAwUKDgoLCgQEAAIAEgMGCFIKDAoFBAACAAYSAwYIGQoMCgUEAAIAARIDBhosCgwKBQQAAgADEgMGLzEKDAoFBAACAAgSAwYyUQoMCgUEAAIAChIDBjNQCgwKBQQAAgAKEgMGPVAKCgoCBAESBAoADQEKCgoDBAEBEgMKCBkKCwoEBAECABIDDAQjCgwKBQQBAgAFEgMMBAgKDAoFBAECAAESAwwJDAoMCgUEAQIAAxIDDA8QCgwKBQQBAgAIEgMMESIKDAoFBAECAAoSAwwSIQoMCgUEAQIAChIDDBwhYgZwcm90bzM=';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'pgquery.proto',
            messages: [
                new File\MessageDescriptor('pg_query.Node', \PgQuery\Node::class),
                new File\MessageDescriptor('pg_query.RTEPermissionInfo', \PgQuery\RTEPermissionInfo::class),
            ],
        ));
    }
}
