<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: php_namespace.proto
 */

declare(strict_types=1);

namespace Thesis\Api\V1;

use Override;
use Thesis\Protobuf\Pool;
use Thesis\Protobuf\Pool\File;

/**
 * @api
 */
final readonly class PhpNamespaceDescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'ChNwaHBfbmFtZXNwYWNlLnByb3RvEgt0ZXN0LmFwaS52MSINCgtUZXN0UmVxdWVzdEIZ+AEBwgIDS2VrygINVGhlc2lzXEFwaVxWMUpdCgYSBAAABxYKCAoBDBIDAAASCggKAQgSAwIAKQoJCgIIKRIDAgApCggKAQgSAwMAIAoJCgIIKBIDAwAgCggKAQISAwUAFAoJCgIEABIDBwAWCgoKAwQAARIDBwgTYgZwcm90bzM=';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'php_namespace.proto',
            messages: [
                new File\MessageDescriptor('test.api.v1.TestRequest', \Thesis\Api\V1\TestRequest::class),
            ],
        ));
    }
}
