<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: php_namespace.proto
 */

declare(strict_types=1);

namespace Thesis\Api\V1;

/**
 * @api
 */
final readonly class TestRequest {}
