<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto3/test.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1;

use Override;
use Thesis\Protobuf\Pool;
use Thesis\Protobuf\Pool\File;

/**
 * @api
 */
final readonly class Proto3TestDescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'ChFwcm90bzMvdGVzdC5wcm90bxIMcHJvdG8uYXBpLnYxIroBCgtUZXN0UmVxdWVzdBIhCgxzdHJpbmdfdmFsdWUYASABKAlSC3N0cmluZ1ZhbHVlEjcKFW9wdGlvbmFsX3N0cmluZ192YWx1ZRgCIAEoCUgBUhNvcHRpb25hbFN0cmluZ1ZhbHVliAEBEhQKBXBob25lGAMgASgJUgVwaG9uZRIUCgVlbWFpbBgEIAEoCVIFZW1haWxCCQoHY29udGFjdEIYChZfb3B0aW9uYWxfc3RyaW5nX3ZhbHVlSroCCgYSBAAACwEKCAoBDBIDAAASCggKAQISAwIAFQoKCgIEABIEBAALAQoKCgMEAAESAwQIEwoLCgQEAAIAEgMFBBwKDAoFBAACAAUSAwUECgoMCgUEAAIAARIDBQsXCgwKBQQAAgADEgMFGhsKCwoEBAACARIDBgQuCgwKBQQAAgEEEgMGBAwKDAoFBAACAQUSAwYNEwoMCgUEAAIBARIDBhQpCgwKBQQAAgEDEgMGLC0KDAoEBAAIABIEBwQKBQoMCgUEAAgAARIDBwoRCgsKBAQAAgISAwgIGQoMCgUEAAICBRIDCAgOCgwKBQQAAgIBEgMIDxQKDAoFBAACAgMSAwgXGAoLCgQEAAIDEgMJCBkKDAoFBAACAwUSAwkIDgoMCgUEAAIDARIDCQ8UCgwKBQQAAgMDEgMJFxhiBnByb3RvMw==';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'proto3/test.proto',
            messages: [
                new File\MessageDescriptor('proto.api.v1.TestRequest', \Proto\Api\V1\TestRequest\ContactEmail::class),
            ],
        ));
    }
}
