<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: registry_collision.proto
 */

declare(strict_types=1);

namespace Registry\Collision;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class DescriptorRegistry2 implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'ChhyZWdpc3RyeV9jb2xsaXNpb24ucHJvdG8SEnJlZ2lzdHJ5LmNvbGxpc2lvbiIqChJEZXNjcmlwdG9yUmVnaXN0cnkSFAoFdmFsdWUYASABKAlSBXZhbHVlSogCCgYSBAAACAEKCAoBDBIDAAASCggKAQISAwIAGwqmAQoCBAASBAYACAEamQEgQSB1c2VyIG1lc3NhZ2UgdGhhdCBhbHJlYWR5IG9jY3VwaWVzIHRoZSBjbGFzcyBuYW1lIHRoZSBkZXNjcmlwdG9yIHJlZ2lzdHJ5CiB3b3VsZCBvdGhlcndpc2UgdGFrZS4gR2VuZXJhdGlvbiBtdXN0IHN1Y2NlZWQgYnkgcmVuYW1pbmcgb3Vycywgbm90IGVycm9yLgoKCgoDBAABEgMGCBoKCwoEBAACABIDBwQVCgwKBQQAAgAFEgMHBAoKDAoFBAACAAESAwcLEAoMCgUEAAIAAxIDBxMUYgZwcm90bzM=';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'registry_collision.proto',
            messages: [
                new File\MessageDescriptor('registry.collision.DescriptorRegistry', \Registry\Collision\DescriptorRegistry::class),
            ],
        ));
    }
}
