<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: registry_collision.proto
 */

declare(strict_types=1);

namespace Registry\Collision;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * A user message that already occupies the class name the descriptor registry
 * would otherwise take. Generation must succeed by renaming ours, not error.
 */
final readonly class DescriptorRegistry
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $value = '',
    ) {}
}
