<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: auth_v1.proto
 */

declare(strict_types=1);

namespace Thesis\Auth\V1;

use Override;
use Thesis\Protobuf\Pool;
use Thesis\Protobuf\Pool\File;

/**
 * @api
 */
final readonly class AuthV1DescriptorRegistry implements Pool\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Cg1hdXRoX3YxLnByb3RvEg5UaGVzaXMuQXV0aC5WMRoRcHJvdG9zL2F1dGgucHJvdG8yTQoLQXV0aFNlcnZpY2USPgoFTG9naW4SGS5UaGVzaXMuQXV0aC5Mb2dpblJlcXVlc3QaGi5UaGVzaXMuQXV0aC5Mb2dpblJlc3BvbnNlSnYKBhIEAAAIAQoICgEMEgMAABIKCAoBAhIDAgAXCgkKAgMAEgMEABsKCgoCBgASBAYACAEKCgoDBgABEgMGCBMKCwoEBgACABIDBwQ+CgwKBQYAAgABEgMHCA0KDAoFBgACAAISAwcOHwoMCgUGAAIAAxIDByo8YgZwcm90bzM=';

    #[Override]
    public function register(Pool\Registry $pool): void
    {
        $pool->add(Pool\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'auth_v1.proto',
            dependencies: [
                'protos/auth.proto',
            ],
            services: [
                new File\ServiceDescriptor(
                    name: 'Thesis.Auth.V1.AuthService',
                    clientFqcn: \Thesis\Auth\V1\AuthServiceClient::class,
                    serverFqcn: \Thesis\Auth\V1\AuthServiceServer::class,
                ),
            ],
        ));
    }
}
