<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto2/test.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1;

/**
 * @api
 *
 * Enum comment.
 */
enum Foo: int
{
    /** Case comment. */
    case FOO_UNSPECIFIED = 0;
    case FOO_BAR = 1;
    case FOO_BAZ = 2;
}
