<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto2.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1\TestRequest\Nested\Deep;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class UnionEmail implements \Proto\Api\V1\TestRequest\Nested\Deep\Union
{
    public function __construct(
        #[Reflection\Field(3, Reflection\StringT::T)]
        public ?string $email = null,
    ) {}
}
