<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: pg_query.proto
 */

declare(strict_types=1);

namespace PgQuery\Node;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class NodeRTEPermissionInfo implements \PgQuery\Node\Node
{
    public function __construct(
        #[Reflection\Field(99, new Reflection\ObjectT(\PgQuery\RTEPermissionInfo::class))]
        public ?\PgQuery\RTEPermissionInfo $RTEPermissionInfo = null,
    ) {}
}
