<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: protos/queue.proto
 */

declare(strict_types=1);

namespace Thesis\Queue;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class PullRequest
{
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public int $qos = 0,
    ) {}
}
