<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: pgquery.proto
 */

declare(strict_types=1);

namespace PgQuery\Node;

/**
 * @api
 * @phpstan-sealed (
 *   NodeRTEPermissionInfo
 * )
 */
interface Node {}
