<?php

declare(strict_types=1);

namespace Thesis\Protoc\Plugin\Mapping;

use Thesis\Protoc\Exception\InvalidNamespaceMapping;

/**
 * Relocation table for protobuf fully qualified names.
 *
 * Thesis is an alternative runtime, so the code it generates for well known packages
 * (google.protobuf, google.rpc, …) must not occupy the same PHP namespaces as the code
 * generated by google/protobuf, otherwise both runtimes cannot live in one project.
 * The table answers a single question: under which PHP namespace a type is generated
 * and referenced.
 *
 * The rewriting never leaves PHP: protobuf names themselves — the ones stored in
 * descriptors, sent in Any type urls and answered by server reflection — stay exactly
 * as the schema declares them, otherwise no other language would understand us.
 *
 * Names are rewritten in a single pass: the result of a rule is never fed into another one.
 *
 * @api
 */
final readonly class TypeMap
{
    private const string PATTERN_SUFFIX = PatternRule::SUFFIX;
    private const string SEGMENT_PATTERN = '/^[A-Za-z_][A-Za-z0-9_]*$/';

    /** @var list<Rule> */
    public array $rules;

    /**
     * @param list<Rule> $rules
     */
    public function __construct(array $rules = [])
    {
        usort($rules, static fn(Rule $a, Rule $b): int => $b->priority() <=> $a->priority());

        $this->rules = $rules;
    }

    /**
     * @throws InvalidNamespaceMapping
     */
    public static function fromFile(string $file): self
    {
        $json = @file_get_contents($file);

        if ($json === false) {
            throw new InvalidNamespaceMapping("Namespace mapping file '{$file}' cannot be read.");
        }

        return self::fromJson($json, $file);
    }

    /**
     * @throws InvalidNamespaceMapping
     */
    public static function fromJson(string $json, string $source = 'namespace mapping'): self
    {
        try {
            $mapping = json_decode($json, associative: true, flags: JSON_THROW_ON_ERROR);
        } catch (\JsonException $e) {
            throw new InvalidNamespaceMapping("Namespace mapping '{$source}' is not a valid json: {$e->getMessage()}.", previous: $e);
        }

        if (!\is_array($mapping) || array_is_list($mapping)) {
            throw new InvalidNamespaceMapping("Namespace mapping '{$source}' must be a json object.");
        }

        $rules = $mapping['rules'] ?? [];

        if (!\is_array($rules) || !array_is_list($rules)) {
            throw new InvalidNamespaceMapping("Namespace mapping '{$source}' must contain a list of rules under the 'rules' key.");
        }

        $parsed = [];
        $seen = [];

        /** @var mixed $rule */
        foreach ($rules as $index => $rule) {
            $parsed[] = $parsedRule = self::parseRule($rule, $source, $index);

            $declaration = $parsedRule->declaration();

            if (isset($seen[$declaration])) {
                throw new InvalidNamespaceMapping("Namespace mapping '{$source}' declares '{$declaration}' more than once.");
            }

            $seen[$declaration] = true;
        }

        return new self($parsed);
    }

    /**
     * @param string $type fully qualified protobuf type name, with or without the leading dot
     * @return ?non-empty-string rewritten name or null when no rule matches
     */
    public function rewriteType(string $type): ?string
    {
        $name = ltrim($type, '.');

        if ($name === '') {
            return null;
        }

        foreach ($this->rules as $rule) {
            $rewritten = $rule->rewriteType($name);

            if ($rewritten !== null) {
                return $rewritten;
            }
        }

        return null;
    }

    /**
     * @return ?non-empty-string rewritten package or null when no rule matches
     */
    public function rewritePackage(string $package): ?string
    {
        foreach ($this->rules as $rule) {
            $rewritten = $rule->rewritePackage($package);

            if ($rewritten !== null) {
                return $rewritten;
            }
        }

        return null;
    }

    /**
     * @throws InvalidNamespaceMapping
     */
    private static function parseRule(mixed $rule, string $source, int|string $index): Rule
    {
        $at = "rule #{$index} of namespace mapping '{$source}'";

        if (!\is_array($rule)) {
            throw new InvalidNamespaceMapping("The {$at} must be a json object with 'from' and 'to' keys.");
        }

        if (($unknown = array_diff(array_keys($rule), ['from', 'to'])) !== []) {
            throw new InvalidNamespaceMapping(\sprintf('The %s contains unknown keys: %s.', $at, implode(', ', array_map(strval(...), $unknown))));
        }

        $from = self::parseName($rule['from'] ?? null, 'from', $at);
        $to = self::parseName($rule['to'] ?? null, 'to', $at);

        $fromIsPattern = str_ends_with($from, self::PATTERN_SUFFIX);
        $toIsPattern = str_ends_with($to, self::PATTERN_SUFFIX);

        if ($fromIsPattern !== $toIsPattern) {
            throw new InvalidNamespaceMapping("The {$at} mixes a pattern with an exact name: '{$from}' → '{$to}'. Either both or neither must end with '" . self::PATTERN_SUFFIX . "'.");
        }

        if ($fromIsPattern && $toIsPattern) {
            return new PatternRule(
                self::validateName(substr($from, 0, -\strlen(self::PATTERN_SUFFIX)), 'from', $at),
                self::validateName(substr($to, 0, -\strlen(self::PATTERN_SUFFIX)), 'to', $at),
            );
        }

        $fromName = self::validateName($from, 'from', $at);
        $toName = self::validateName($to, 'to', $at);

        // Only the namespace of a type may be rewritten. Renaming a type would mean
        // that the generated class no longer matches the descriptor it is registered
        // with, so we reject it instead of generating code nobody can use.
        if (self::lastSegment($fromName) !== self::lastSegment($toName)) {
            throw new InvalidNamespaceMapping("The {$at} renames a type: '{$fromName}' → '{$toName}'. Only the namespace a type lives in can be rewritten.");
        }

        return new ExactRule($fromName, $toName);
    }

    /**
     * @return non-empty-string
     * @throws InvalidNamespaceMapping
     */
    private static function parseName(mixed $name, string $key, string $at): string
    {
        if (!\is_string($name) || $name === '') {
            throw new InvalidNamespaceMapping("The {$at} must contain a non-empty string under the '{$key}' key.");
        }

        return $name;
    }

    /**
     * @return non-empty-string
     * @throws InvalidNamespaceMapping
     */
    private static function validateName(string $name, string $key, string $at): string
    {
        $segments = explode('.', $name);

        foreach ($segments as $segment) {
            if (preg_match(self::SEGMENT_PATTERN, $segment) !== 1) {
                throw new InvalidNamespaceMapping("The '{$key}' name '{$name}' of the {$at} is not a valid protobuf name.");
            }
        }

        \assert($name !== '');

        return $name;
    }

    private static function lastSegment(string $name): string
    {
        $segments = explode('.', $name);

        return $segments[\count($segments) - 1];
    }
}
