<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto3.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1;

/**
 * @api
 */
enum Kind: int
{
    case KIND_UNSPECIFIED = 0;
    case KIND_FIRST = 1;
    case KIND_SECOND = 2;
}
