<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto3.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class Proto3DescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'Cgxwcm90bzMucHJvdG8SDHByb3RvLmFwaS52MSLHAgoLVGVzdFJlcXVlc3QSIQoMc3RyaW5nX3ZhbHVlGAEgASgJUgtzdHJpbmdWYWx1ZRI3ChVvcHRpb25hbF9zdHJpbmdfdmFsdWUYAiABKAlIAVITb3B0aW9uYWxTdHJpbmdWYWx1ZYgBARI3Cg1pbXBsaWNpdF9raW5kGAUgASgOMhIucHJvdG8uYXBpLnYxLktpbmRSDGltcGxpY2l0S2luZBI8Cg1vcHRpb25hbF9raW5kGAYgASgOMhIucHJvdG8uYXBpLnYxLktpbmRIAlIMb3B0aW9uYWxLaW5kiAEBEhYKBXBob25lGAMgASgJSABSBXBob25lEhYKBWVtYWlsGAQgASgJSABSBWVtYWlsQgkKB2NvbnRhY3RCGAoWX29wdGlvbmFsX3N0cmluZ192YWx1ZUIQCg5fb3B0aW9uYWxfa2luZCo9CgRLaW5kEhQKEEtJTkRfVU5TUEVDSUZJRUQQABIOCgpLSU5EX0ZJUlNUEAESDwoLS0lORF9TRUNPTkQQAkrJBAoGEgQAABMBCggKAQwSAwAAEgoICgECEgMCABUKCgoCBQASBAQACAEKCgoDBQABEgMEBQkKCwoEBQACABIDBQQZCgwKBQUAAgABEgMFBBQKDAoFBQACAAISAwUXGAoLCgQFAAIBEgMGBBMKDAoFBQACAQESAwYEDgoMCgUFAAIBAhIDBhESCgsKBAUAAgISAwcEFAoMCgUFAAICARIDBwQPCgwKBQUAAgICEgMHEhMKCgoCBAASBAoAEwEKCgoDBAABEgMKCBMKCwoEBAACABIDCwQcCgwKBQQAAgAFEgMLBAoKDAoFBAACAAESAwsLFwoMCgUEAAIAAxIDCxobCgsKBAQAAgESAwwELgoMCgUEAAIBBBIDDAQMCgwKBQQAAgEFEgMMDRMKDAoFBAACAQESAwwUKQoMCgUEAAIBAxIDDCwtCgsKBAQAAgISAw0EGwoMCgUEAAICBhIDDQQICgwKBQQAAgIBEgMNCRYKDAoFBAACAgMSAw0ZGgoLCgQEAAIDEgMOBCQKDAoFBAACAwQSAw4EDAoMCgUEAAIDBhIDDg0RCgwKBQQAAgMBEgMOEh8KDAoFBAACAwMSAw4iIwoMCgQEAAgAEgQPBBIFCgwKBQQACAABEgMPChEKCwoEBAACBBIDEAgZCgwKBQQAAgQFEgMQCA4KDAoFBAACBAESAxAPFAoMCgUEAAIEAxIDEBcYCgsKBAQAAgUSAxEIGQoMCgUEAAIFBRIDEQgOCgwKBQQAAgUBEgMRDxQKDAoFBAACBQMSAxEXGGIGcHJvdG8z';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'proto3.proto',
            messages: [
                new File\MessageDescriptor('proto.api.v1.TestRequest', \Proto\Api\V1\TestRequest::class),
            ],
            enums: [
                new File\EnumDescriptor('proto.api.v1.Kind', \Proto\Api\V1\Kind::class),
            ],
        ));
    }
}
