<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto3.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class TestRequest
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $stringValue = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public ?string $optionalStringValue = null,
        #[Reflection\Field(5, new Reflection\EnumT(\Proto\Api\V1\Kind::class))]
        public \Proto\Api\V1\Kind $implicitKind = \Proto\Api\V1\Kind::KIND_UNSPECIFIED,
        #[Reflection\Field(6, new Reflection\EnumT(\Proto\Api\V1\Kind::class))]
        public ?\Proto\Api\V1\Kind $optionalKind = null,
        #[Reflection\OneOf([\Proto\Api\V1\TestRequest\ContactPhone::class, \Proto\Api\V1\TestRequest\ContactEmail::class])]
        public ?\Proto\Api\V1\TestRequest\Contact $contact = null,
    ) {}
}
