<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 */

declare(strict_types=1);

\Thesis\Protobuf\Registry\Pool::get()->register(
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Test\Deps\Custom\DescriptorRegistry()),
    new \Thesis\Protobuf\Registry\OnceRegistrar(new \Test\Main\V1\DescriptorRegistry()),
);
