<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: naming.proto
 */

declare(strict_types=1);

namespace Naming;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Naming
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $userId = '',
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $httpStatusCode = '',
        #[Reflection\Field(3, Reflection\Uint64T::T)]
        public \BcMath\Number $ID = new \BcMath\Number(0),
        #[Reflection\Field(4, Reflection\Uint64T::T)]
        public \BcMath\Number $TTL = new \BcMath\Number(0),
        #[Reflection\Field(5, Reflection\StringT::T)]
        public string $URL = '',
        #[Reflection\Field(6, Reflection\StringT::T)]
        public string $userID = '',
        #[Reflection\Field(7, Reflection\StringT::T)]
        public string $leaseTTL = '',
        #[Reflection\Field(8, Reflection\StringT::T)]
        public string $IDPrefix = '',
        #[Reflection\Field(9, Reflection\StringT::T)]
        public string $alreadyCamel = '',
        #[Reflection\Field(10, Reflection\StringT::T)]
        public string $leaseID = '',
        #[Reflection\Field(11, Reflection\StringT::T)]
        public string $HTTPStatus = '',
        #[Reflection\Field(12, Reflection\StringT::T)]
        public string $a = '',
        #[Reflection\Field(13, Reflection\StringT::T)]
        public string $field2 = '',
        #[Reflection\Field(14, Reflection\StringT::T)]
        public string $trailing = '',
        #[Reflection\Field(15, Reflection\StringT::T)]
        public string $Leading = '',
    ) {}
}
