<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: protos/auth.proto
 */

declare(strict_types=1);

namespace Thesis\Auth;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class LoginRequest
{
    public function __construct(
        #[Reflection\Field(2, Reflection\StringT::T)]
        public string $user = '',
        #[Reflection\Field(3, Reflection\StringT::T)]
        public string $password = '',
    ) {}
}
