<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: snake_case/snake_case.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1\TestRequest\NestedMessage\Deep;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class UnionPhone implements \Proto\Api\V1\TestRequest\NestedMessage\Deep\Union
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $phone = '',
    ) {}
}
