<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: status.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Rpc;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class DescriptorRegistry implements Registry\Registrar
{
    private const string STATUS_DESCRIPTOR_BUFFER = 'CgxzdGF0dXMucHJvdG8SCmdvb2dsZS5ycGMaH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8i6QIKBlN0YXR1cxISCgRjb2RlGAEgASgFUgRjb2RlEisKBGtpbmQYAiABKA4yFy5nb29nbGUucnBjLlN0YXR1cy5LaW5kUgRraW5kEjEKBmRldGFpbBgDIAEoCzIZLmdvb2dsZS5ycGMuU3RhdHVzLkRldGFpbFIGZGV0YWlsEjkKCmNyZWF0ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wUgljcmVhdGVkQXQSFAoEdGV4dBgFIAEoCUgAUgR0ZXh0EjsKCnN0cnVjdHVyZWQYBiABKAsyGS5nb29nbGUucnBjLlN0YXR1cy5EZXRhaWxIAFIKc3RydWN0dXJlZBogCgZEZXRhaWwSFgoGcmVhc29uGAEgASgJUgZyZWFzb24iMAoES2luZBIUChBLSU5EX1VOU1BFQ0lGSUVEEAASEgoOS0lORF9SRVRSWUFCTEUQAUIJCgdwYXlsb2FkMj4KDVN0YXR1c1NlcnZpY2USLQoDR2V0EhIuZ29vZ2xlLnJwYy5TdGF0dXMaEi5nb29nbGUucnBjLlN0YXR1c0rFBgoGEgQAAB8BCggKAQwSAwAAEgoICgECEgMCABMKCQoCAwASAwQAKQqFAQoCBAASBAgAGwEaeSBUaGUgcGFja2FnZSBpcyByZWxvY2F0ZWQgaW50byBUaGVzaXNcR29vZ2xlXFJwYyBieSBtYXAuanNvbiwgd2hpbGUgdGhlIHByb3RvYnVmCiBuYW1lIG9mIGV2ZXJ5IHR5cGUgc3RheXMgZ29vZ2xlLnJwYy4qLgoKCgoDBAABEgMICA4KDAoEBAAEABIECQQMBQoMCgUEAAQAARIDCQkNCg0KBgQABAACABIDCggdCg4KBwQABAACAAESAwoIGAoOCgcEAAQAAgACEgMKGxwKDQoGBAAEAAIBEgMLCBsKDgoHBAAEAAIBARIDCwgWCg4KBwQABAACAQISAwsZGgoMCgQEAAMAEgQOBBAFCgwKBQQAAwABEgMODBIKDQoGBAADAAIAEgMPCBoKDgoHBAADAAIABRIDDwgOCg4KBwQAAwACAAESAw8PFQoOCgcEAAMAAgADEgMPGBkKCwoEBAACABIDEgQTCgwKBQQAAgAFEgMSBAkKDAoFBAACAAESAxIKDgoMCgUEAAIAAxIDEhESCgsKBAQAAgESAxMEEgoMCgUEAAIBBhIDEwQICgwKBQQAAgEBEgMTCQ0KDAoFBAACAQMSAxMQEQoLCgQEAAICEgMUBBYKDAoFBAACAgYSAxQECgoMCgUEAAICARIDFAsRCgwKBQQAAgIDEgMUFBUKCwoEBAACAxIDFQQtCgwKBQQAAgMGEgMVBB0KDAoFBAACAwESAxUeKAoMCgUEAAIDAxIDFSssCgwKBAQACAASBBcEGgUKDAoFBAAIAAESAxcKEQoLCgQEAAIEEgMYCBgKDAoFBAACBAUSAxgIDgoMCgUEAAIEARIDGA8TCgwKBQQAAgQDEgMYFhcKCwoEBAACBRIDGQgeCgwKBQQAAgUGEgMZCA4KDAoFBAACBQESAxkPGQoMCgUEAAIFAxIDGRwdCgoKAgYAEgQdAB8BCgoKAwYAARIDHQgVCgsKBAYAAgASAx4EJQoMCgUGAAIAARIDHggLCgwKBQYAAgACEgMeDBIKDAoFBgACAAMSAx4dI2IGcHJvdG8z';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::STATUS_DESCRIPTOR_BUFFER), new File(
            name: 'status.proto',
            dependencies: [
                'google/protobuf/timestamp.proto',
            ],
            messages: [
                new File\MessageDescriptor('google.rpc.Status', \Thesis\Google\Rpc\Status::class),
                new File\MessageDescriptor('google.rpc.Status.Detail', \Thesis\Google\Rpc\Status\Detail::class),
            ],
            enums: [
                new File\EnumDescriptor('google.rpc.Status.Kind', \Thesis\Google\Rpc\Status\Kind::class),
            ],
            services: [
                new File\ServiceDescriptor(
                    name: 'google.rpc.StatusService',
                    methods: [
                        new File\MethodDescriptor('Get', false, false),
                    ],
                ),
            ],
        ));
    }
}
