<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: status.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Rpc;

use Amp\Cancellation;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
interface StatusServiceServer
{
    public function get(
        \Thesis\Google\Rpc\Status $request,
        Metadata $md,
        Cancellation $cancellation,
    ): \Thesis\Google\Rpc\Status;
}
