<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: status.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Rpc;

use Amp\Cancellation;
use Amp\NullCancellation;
use Thesis\Grpc;
use Thesis\Grpc\Client;
use Thesis\Grpc\Exception\ClientStreamIsClosed;
use Thesis\Grpc\InvokeError;
use Thesis\Grpc\Metadata;

/**
 * @api
 */
final readonly class StatusServiceClient
{
    public function __construct(
        private Client $client,
    ) {}

    /**
     * @throws ClientStreamIsClosed
     * @throws InvokeError
     */
    public function get(
        \Thesis\Google\Rpc\Status $request,
        Metadata $md = new Metadata(),
        Cancellation $cancellation = new NullCancellation(),
    ): \Thesis\Google\Rpc\Status {
        /** @var Client\Invoke<\Thesis\Google\Rpc\Status, \Thesis\Google\Rpc\Status> $invoke */
        $invoke = new Client\Invoke(
            method: '/google.rpc.StatusService/Get',
            output: \Thesis\Google\Rpc\Status::class,
            type: Grpc\RpcType::Unary,
        );

        return $this->client->invoke(
            request: $request,
            invoke: $invoke,
            md: $md,
            cancellation: $cancellation,
        );
    }
}
