<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: status.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Rpc;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * The package is relocated into Thesis\Google\Rpc by map.json, while the protobuf
 * name of every type stays google.rpc.*.
 */
final readonly class Status
{
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public int $code = 0,
        #[Reflection\Field(2, new Reflection\EnumT(\Thesis\Google\Rpc\Status\Kind::class))]
        public \Thesis\Google\Rpc\Status\Kind $kind = \Thesis\Google\Rpc\Status\Kind::KIND_UNSPECIFIED,
        #[Reflection\Field(3, new Reflection\ObjectT(\Thesis\Google\Rpc\Status\Detail::class))]
        public ?\Thesis\Google\Rpc\Status\Detail $detail = null,
        #[Reflection\Field(4, new Reflection\ObjectT(\Thesis\Google\Protobuf\Timestamp::class))]
        public ?\Thesis\Google\Protobuf\Timestamp $createdAt = null,
        #[Reflection\OneOf([\Thesis\Google\Rpc\Status\PayloadText::class, \Thesis\Google\Rpc\Status\PayloadStructured::class])]
        public ?\Thesis\Google\Rpc\Status\Payload $payload = null,
    ) {}
}
