<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.x-dev
 *   protoc               — v6.32.1
 * Source: status.proto
 */

declare(strict_types=1);

namespace Thesis\Google\Rpc;

use Override;
use Thesis\Grpc;
use Thesis\Grpc\Server;

/**
 * @api
 */
final readonly class StatusServiceServerRegistry implements Server\ServiceRegistry
{
    public function __construct(
        private \Thesis\Google\Rpc\StatusServiceServer $server,
    ) {}

    #[Override]
    public function services(): iterable
    {
        yield new Server\Service('google.rpc.StatusService', [
            new Server\Rpc(
                handle: new Server\Handle('Get', \Thesis\Google\Rpc\Status::class),
                handler: new Server\UnaryHandler($this->server->get(...)),
                type: Grpc\RpcType::Unary,
            ),
        ]);
    }
}
