<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: snake_case.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class TestRequest
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Proto\Api\V1\TestRequest\NestedMessage::class))]
        public ?\Proto\Api\V1\TestRequest\NestedMessage $nested = null,
        #[Reflection\Field(5, new Reflection\ObjectT(\Proto\Api\V1\TestRequest\NestedMessage\Deep::class))]
        public ?\Proto\Api\V1\TestRequest\NestedMessage\Deep $nestedDeep = null,
        #[Reflection\OneOf([
            \Proto\Api\V1\TestRequest\XFieldNumber::class,
            \Proto\Api\V1\TestRequest\XFieldCol::class,
            \Proto\Api\V1\TestRequest\XFieldDeepEnum::class,
        ])]
        public ?\Proto\Api\V1\TestRequest\XField $xField = null,
    ) {}
}
