<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: main.proto
 */

declare(strict_types=1);

namespace Test\Main\V1;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class MainDescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'CgptYWluLnByb3RvEgx0ZXN0Lm1haW4udjEaCWRlcC5wcm90byI3CgtNYWluTWVzc2FnZRIoCgNkZXAYASABKAsyFi5kZXAucGtnLnYxLkRlcE1lc3NhZ2VSA2RlcEp2CgYSBAAACAEKCAoBDBIDAAASCggKAQISAwIAFQoJCgIDABIDBAATCgoKAgQAEgQGAAgBCgoKAwQAARIDBggTCgsKBAQAAgASAwcCIAoMCgUEAAIABhIDBwIXCgwKBQQAAgABEgMHGBsKDAoFBAACAAMSAwceH2IGcHJvdG8z';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'main.proto',
            dependencies: [
                'dep.proto',
            ],
            messages: [
                new File\MessageDescriptor('test.main.v1.MainMessage', \Test\Main\V1\MainMessage::class),
            ],
        ));
    }
}
