<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: main.proto
 */

declare(strict_types=1);

namespace Test\Main\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class MainMessage
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Test\Deps\Custom\DepMessage::class))]
        public ?\Test\Deps\Custom\DepMessage $dep = null,
    ) {}
}
