<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: required_message.proto
 */

declare(strict_types=1);

namespace Proto\Required\V1;

use Override;
use Thesis\Protobuf\Registry;
use Thesis\Protobuf\Registry\File;

/**
 * @api
 */
final readonly class RequiredMessageDescriptorRegistry implements Registry\Registrar
{
    private const string DESCRIPTOR_BUFFER = 'ChZyZXF1aXJlZF9tZXNzYWdlLnByb3RvEhFwcm90by5yZXF1aXJlZC52MSIbCgVJbm5lchISCgRuYW1lGAEgASgJUgRuYW1lIosBCgdSZXF1ZXN0Ej8KDnJlcXVpcmVkX2lubmVyGAEgAigLMhgucHJvdG8ucmVxdWlyZWQudjEuSW5uZXJSDXJlcXVpcmVkSW5uZXISPwoOb3B0aW9uYWxfaW5uZXIYAiABKAsyGC5wcm90by5yZXF1aXJlZC52MS5Jbm5lclINb3B0aW9uYWxJbm5lckqbAgoGEgQAAAsBCggKAQwSAwAAEgoICgECEgMCABoKCgoCBAASBAQABgEKCgoDBAABEgMECA0KCwoEBAACABIDBQQdCgwKBQQAAgAEEgMFBAwKDAoFBAACAAUSAwUNEwoMCgUEAAIAARIDBRQYCgwKBQQAAgADEgMFGxwKCgoCBAESBAgACwEKCgoDBAEBEgMICA8KCwoEBAECABIDCQQmCgwKBQQBAgAEEgMJBAwKDAoFBAECAAYSAwkNEgoMCgUEAQIAARIDCRMhCgwKBQQBAgADEgMJJCUKCwoEBAECARIDCgQmCgwKBQQBAgEEEgMKBAwKDAoFBAECAQYSAwoNEgoMCgUEAQIBARIDChMhCgwKBQQBAgEDEgMKJCU=';

    #[Override]
    public function register(Registry\Pool $pool): void
    {
        $pool->add(Registry\Descriptor::base64(self::DESCRIPTOR_BUFFER), new File(
            name: 'required_message.proto',
            messages: [
                new File\MessageDescriptor('proto.required.v1.Inner', \Proto\Required\V1\Inner::class),
                new File\MessageDescriptor('proto.required.v1.Request', \Proto\Required\V1\Request::class),
            ],
        ));
    }
}
