<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: required_message.proto
 */

declare(strict_types=1);

namespace Proto\Required\V1;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Request
{
    public function __construct(
        #[Reflection\Field(1, new Reflection\ObjectT(\Proto\Required\V1\Inner::class))]
        public \Proto\Required\V1\Inner $requiredInner,
        #[Reflection\Field(2, new Reflection\ObjectT(\Proto\Required\V1\Inner::class))]
        public ?\Proto\Required\V1\Inner $optionalInner = null,
    ) {}
}
