<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.x-dev
 *   protoc               — v6.32.1
 * Source: proto2.proto
 */

declare(strict_types=1);

namespace Proto\Api\V1\TestRequest\Nested;

use Thesis\Protobuf\Reflection;

/**
 * @api
 */
final readonly class Deep
{
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public string $name = '',
        #[Reflection\Field(4, new Reflection\EnumT(\Proto\Api\V1\TestRequest\Nested\Deep\DeepEnum::class))]
        public ?\Proto\Api\V1\TestRequest\Nested\Deep\DeepEnum $deepEnum = null,
        #[Reflection\OneOf([\Proto\Api\V1\TestRequest\Nested\Deep\UnionPhone::class, \Proto\Api\V1\TestRequest\Nested\Deep\UnionEmail::class])]
        public ?\Proto\Api\V1\TestRequest\Nested\Deep\Union $union = null,
    ) {}
}
